local_apps/petricko/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic.simple import direct_to_template

from news.views import new_view, news_list_view
from views import category_view

urlpatterns = patterns('',
    url(r'^novinka/(?P<new_url_key>[a-zA-Z0-9-]+)$',
        new_view,
        {"template": "petricko/new.html"},
        name="petricko.new", ),
    url(r'^(?P<category_url_key>[a-zA-Z0-9-]+)$',
        category_view,
        name="petricko.category", ),
)

local_apps/petricko/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils.encoding import force_unicode

from image_cropping.fields import ImageRatioField, ImageCropField
# {% thumbnail new.img 143x115 box=new.img_crop crop detail %}

class Category(models.Model):
    order = models.IntegerField(default=0, max_length=2)
    name = models.CharField(max_length=255)
    url_key = models.CharField(max_length=255, unique=True, blank=True)
    img = ImageCropField(upload_to='uploaded_images', blank=True, null=True)
    img_crop = ImageRatioField('img', '960x300')
    description = models.TextField(blank=True, null=True)

    show_in_side_menu = models.BooleanField()

    def __unicode__(self):
        return force_unicode("%s " % (self.name))

    def save(self, *args, **kwargs):
        if not self.url_key:
            self.url_key = slugify(self.name)
        return super(Category, self).save(*args, **kwargs)

class Subcategory(models.Model):
    category = models.ForeignKey(Category)

    order = models.IntegerField(default=0, max_length=2)
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return force_unicode("%s " % (self.name))

class Article(models.Model):
    subcategory = models.ForeignKey(Subcategory)

    order = models.IntegerField(default=0, max_length=2)
    name = models.CharField(max_length=255)
    img = ImageCropField(upload_to='uploaded_images', blank=True, null=True)
    img_crop = ImageRatioField('img', '400x200')
    description = models.TextField()

    def __unicode__(self):
        return force_unicode("%s %s" % (self.subcategory.name, self.description[:20]))


class Product(models.Model):
    category = models.ForeignKey(Category, blank=True, null=True)

    order = models.IntegerField(default=0, max_length=2)
    name = models.CharField(max_length=255)
    url_key = models.CharField(max_length=255, unique=True, blank=True)
    img = ImageCropField(upload_to='uploaded_images', blank=True, null=True)
    img_crop = ImageRatioField('img', '400x200')
    description = models.TextField()
    link_to_shop = models.URLField(null=True, blank=True)

    def __unicode__(self):
        return force_unicode("%s " % (self.name))

    def save(self, *args, **kwargs):
        if not self.url_key:
            self.url_key = slugify(self.name)
        return super(Product, self).save(*args, **kwargs)

class Pdf(models.Model):
    product = models.ForeignKey(Product)

    name = models.CharField(max_length=32)
    pdf_file = models.FileField(upload_to="pdf")

    def __unicode__(self):
        return force_unicode("%s" % ( self.name))

local_apps/petricko/views.py
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse

from models import Product, Category


def category_view(request, category_url_key, template="petricko/category.html"):
    obj = get_object_or_404(Category, url_key=category_url_key)
    products = obj.product_set.all().order_by("order", "name")
    subcategory_list = obj.subcategory_set.all().order_by("order", "name")
    if subcategory_list.count():
        template = "petricko/category_sub.html"
    return render_to_response(template,
        {"category":obj,
         "products_list": products,
         "subcategory_list": subcategory_list, },
        context_instance=RequestContext(request))

local_apps/petricko/templates/petricko/base.html
{% load cms_tags sekizai_tags menu_tags %}
<!DOCTYPE html>
<html lang="en_US">
 <head>
 
  <!-- Vytvořil Ondřej Šika & Michael Švarc, (c) 2012 -->
 
  <meta charset="utf_8" />
  {% render_block "css" %}
  <link rel="stylesheet" href="/static/petricko/css/base.css" type="text/css" />
  <link rel="stylesheet" href="/static/petricko/css/bootstrap-forms.css" type="text/css" />
  <!-- <link rel="icon" href="favicon.ico" type="image/x_icon" /> -->

  <title>Petricko</title>
 </head>
 <body>
{% cms_toolbar %}
<div id="main_container">

<div id="header">
    <div id="logo">
    <a href="/"><img src="/static/petricko/img/logo_big.png"></a>
    </div> <!-- logo -->
    
    <a href="http://www.zdravotnicke-potreby.com/"  target="blank"><p id="eshop">E-shop</p></a>
    
    <div id="search_form">
    <form action="/search" method="get">
      <input type="search" id="search_i" name="q" placeholder="Vyhledávaný pojem">
      <input type="submit" value="Hledej" id="search_s" >
    </form>
    </div> <!-- search -->
    
</div> <!-- header -->

<div id="main_menu">
    <ul>
        {% show_menu 0 100 100 100 "petricko/main_menu.html" %}
    </ul>
</div> <!-- main_menu -->

<div id="page_container">

    {# placeholder base_content #}
    {% block base_content %}
    {% block page %}
    <div id="side_bar">
    
        <div class="side_bar_header">
            <img src="/static/petricko/img/left_menu_icon_dalsi_zbbozi.png" class="lm_icon">
            <h2>Další zboží</h2>
        </div>
        
        <div id="side_menu">
            <ul>
                {% for category in side_menu_category_list %}
                    <li class="{%if category.name|length > 25%}dvojradek{%endif%}">
                        <a href="{% url petricko.category category.url_key %}">{{category.name}}</a>
                    </li>
                {% endfor %}
                <li class="">
                    <a href="/individualni-prani/">Individuální přání</a>
                </li>
            </ul>
        </div> <!-- side_menu -->
        <div class="side_bar_header">
            <img src="/static/petricko/img/left_menu_icon_telefon.png" class="lm_icon">
            <h2>Podpora na telefonu</h2>
        </div>
        <img src="/static/petricko/img/telefon_icon_telefon.png" class="lm_t_icon">
        <p class="side_bar_phone">353 822 439</p>
        <h3>Nakupte u nás po telefonu:</h3>
        <img src="/static/petricko/img/telefon_icon_shop.png" class="lm_t_icon">
        <p class="side_bar_phone">353 821 633</p>
        
        <div class="side_bar_header">
            <img src="/static/petricko/img/left_menu_icon_anketa.png" class="lm_icon">
            <h2>Anketa</h2>
            <div style="clear:both;"></div>
            {% load polls_tags %}
            <script src="http://code.jquery.com/jquery.min.js"></script>
            {% poll_queue "anketa" %}
        </div>
    </div> <!-- side_bar -->
    
    <div id="content">
        {% block content %}
        <div id="content_img">
          <h1 style="visibility: hidden;">Petričko - pro život v pohybu</h1>
        </div> <!-- content_img -->
        <div class="section">
            <div class="predni_lajna"><!-- --></div><h2>Nejžádanější zboží</h2><div class="zadni_lajna"><!-- --></div>
            <h3 id="product_luzka"><a href="/polohovaci-luzka">Polohovací lůžka</a></h3>
            <h3 id="product_voziky"><a href="/mechanicke-a-elektricke-invalidni-voziky">Mechanické&nbsp;a&nbsp;elektrické <br /> invalidní vozíky</a></h3>
            <h3 id="product_koupelny"><a href="/pomucky-do-koupelny-a-wc">Pomůcky&nbsp;do<br />koupelny a WC</a></h3>
            <h3 id="product_chuze"><a href="/pomucky-pro-usnadneni-chuze">Pomůcky&nbsp;pro <br />usnadnění chůze</a> </h3>
            
        </div> <!-- section -->
        <div class="section">
            {% block news %}{% endblock %}
        </div> <!-- section -->
        {% endblock content %}
    </div> <!-- content -->
    
    {% endblock page %}
    {% endblock base_content %}
</div> <!-- page_container -->
<div id="footer">
    <div id="footer_left">
        <ul>
            {% show_menu 0 100 100 100 %}
        </ul>
        <p><br /></p>
        <p>2012 &copy; <strong>Petricko s.r.o.</strong>, all rights reserved. Vlastníkem stránek je firma <strong>Petricko s.r.o.</strong></p>
    </div> <!-- footer_left -->
    <div id="footer_right">
        <ul>
            <li class="first">Design by <a href="http://www.michaelsvarc.com">Michael Švarc</a></li>
            <li><a href="http://djangoproject.com">Django 1.4</a> power by <a href="http://ondrejsika.com">Ondřej Šika</a></li>
        </ul>
    </div> <!-- footer_right -->
</div> <!-- footer -->
</div> <!-- main_container -->
{% render_block "js" %}
  </body>
</html>

local_apps/petricko/templates/petricko/category.html
{% extends "petricko/base.html" %}
{% load cms_tags sekizai_tags menu_tags %}
{% load thumbnail markup %}
{% block page %}
    <div class="page_head">
        <img src="{% thumbnail category.img 960x300 box=category.img_crop crop detail %}">
        <h2>{{category.name}}</h2>
        <p>{{category.description|linebreaksbr|markdown}}</p>
    </div>
    {% for product in products_list %}
        <div class="product">
         <h3>{{product.name}}</h3>
            <div class="product_image">
                <img src="{% thumbnail product.img 314x149 box=product.img_crop crop detail %}">
            </div> <!-- product_image -->
            <div class="product_content">
               
                <p>{{product.description|linebreaksbr|markdown}}</p>
            
                <div class="product_bar">
                  <hr class="product_hr" />
                    <div class="product_files">
                        {% for pdf in product.pdf_set.all %}
                            <a href="{{pdf.pdf_file.url}}" class="product_pdf" target="blank"><img src="/static/petricko/img/pdf_icon.png" alt="{{pdf.name}}"><b>{{pdf.name}} </b></a>
                        {% endfor%}
                    </div>
                    <div class="product_on_eshop">
                        <p>
                            {% if product.link_to_shop %}
                                <a href="{{product.link_to_shop}}" target="blank" class="do_eshop">Nakupte u nás</a>
                            {% else %}
                                <a href="http://zdravotnicke-potreby.com" target="blank" class="do_eshop">Nakupte u nás</a>
                            {% endif %}
                        <p>
                    </div>
                </div>
            </div><!-- product_content -->
        </div> <!-- product -->
    {% endfor %}
{% endblock page %}

local_apps/petricko/templates/petricko/category_sub.html
{% extends "petricko/base.html" %}
{% load cms_tags sekizai_tags menu_tags %}
{% load thumbnail %}
{% load markup %}
{% block page %}
    <div class="page_head">
        <img src="{% thumbnail category.img 960x300 box=category.img_crop crop detail %}">
        <h2>{{category.name}}</h2>
        <p>{{category.description}}</p>
    </div>
    <div id="product_boxes">
        {% for product in products_list %}
            {% if product.pdf_set.all.0 %}<a  target="blank" href="{{product.pdf_set.all.0.pdf_file.url}}">{%endif%}<div class="product_box"  style="background: url('{% thumbnail product.img 300x200 box=product.img_crop crop detail %}')"><h3>{{ product.name }}</h3></div>{% if product.pdf_set.all.0 %}</a>{%endif%}
        {% endfor %}
    </div>
        <p>
            <a href="http://zdravotnicke-potreby.com" target="blank" class="do_eshop" style="margin-right:21px;">Náš obchod</a>
        </p>
    <div style="clear:both"></div>
    {% for item in subcategory_list %}
                                                        <div class="product">
                                                    <h3>{{item.name}}</h3>
                                                    {% for article in item.article_set.all %}
                                                        
                                                            <div class="product_image">
                                                                <img src="{% thumbnail article.img 314x149 box=article.img_crop crop detail %}">
                                                            </div> <!-- product_image -->
                                                            <div class="product_content">
                                                                <p>{{ article.description|linebreaksbr|markdown }}</p>
                                                                <div class="product_bar">
                                                                     <hr class="product_hr" />
                                                                <div class="product_files">
                                                                    {% for pdf in product.pdf_set.all %}
                                                                        <a href="{{pdf.pdf_file.url}}" target="blank"><img src="/static/petricko/img/pdf_icon.png" alt="{{pdf.name}}"><b>{{pdf.name}}</b></a>
                                                                    {% endfor%}
                                                                </div>
                                                                </div>
                                                            </div>
                                                      
                                                    {% endfor %}
                                                      </div> <!-- product -->
    {% endfor %}
{% endblock page %}

local_apps/petricko/templates/petricko/cms/home_page.html
{% extends "petricko/base.html" %}
{% load cms_tags %}

{% block news %}
<style type="text/css">
#page_container {
    background: url(/static/petricko/img/index_back.jpg) repeat-y;
}
</style>
  {% placeholder static_page_content %}
{% endblock %}

local_apps/petricko/templates/petricko/cms/static_page.html
{% extends "petricko/base.html" %}
{% load cms_tags %}

{% block base_content %}
  <div id="sps">

  {% placeholder static_page_content %}
  </div><!-- static_page_Style -->
{% endblock %}

local_apps/petricko/templates/petricko/cms/with_sidebar.html
{% extends "petricko/base.html" %}
{% load cms_tags %}

{% block content %}
<style type="text/css">
#page_container {
    background: url(/static/petricko/img/index_back.jpg) repeat-y;
}
</style>
  {% placeholder static_page_content %}
{% endblock %}

local_apps/petricko/templates/petricko/main_menu.html
{% load menu_tags %}
{% for child in children %}
<li class="{% if child.selected %}selected{% endif %}{% if child.ancestor %}ancestor{% endif %}{% if child.sibling %}sibling{% endif %}{% if child.descendant %}descendant{% endif %}{% if child.get_menu_title|length < 8 %} small{% else%} long{% endif %}">
    <a href="{{ child.attr.redirect_url|default:child.get_absolute_url }}">{{ child.get_menu_title }}</a>
    {% if child.children %}
    <ul>
        {% show_menu from_level to_level extra_inactive extra_active template "" "" child %}
    </ul>
    {% endif %}
</li>
{% endfor %}

local_apps/petricko/templates/petricko/new.html
{% extends "petricko/base.html" %}
{% load cms_tags sekizai_tags menu_tags thumbnail %}
{% block page %}
<p><br /></p>
<div class="new_date">{{ new.get_created_at }}</div> <!-- new_date -->
<div class="news_sub">
<h2>{{ new.name }}</h2>
<div class="cistic"></div><!-- cistic -->
<img id="new_detail_img" src="{% thumbnail new.img 286x230 box=new.img_crop crop detail %}">

<div id="new_detail_content">
    <p>{{new.description}}</p>
    <p>{{new.content}}</p>
    <p><br /></p>
    <p class="cist_cele"><a href="/#zadni_lajna_n"><span>Zpět na hlavní stranu</span></a></p>
</div>
</div><!-- news_sub -->
{% endblock page %}

local_apps/petricko/templates/petricko/products_list.html
{% extends "petricko/base.html" %}
{% load thumbnail markup %}
{% block page %}
    {% for product in products_list %}
        <div class="product">
            <div class="product_image">
                <img src="{% thumbnail product.img 314x159 box=product.img_crop crop detail %}">
            </div> <!-- product_image -->
            <div class="product_content">
                <h3>{{product.name}}</h3>
                <p>{{product.description|linebreaksbr|markdown}}</p>
            
                <div class="product_bar">
                                                                     <hr class="product_hr" />
                                                                <div class="product_files">
                                                                    {% for pdf in product.pdf_set.all %}
                                                                        <a href="{{pdf.pdf_file.url}}" target="blank"><img src="/static/petricko/img/pdf_icon.png" alt="{{pdf.name}}"><b>{{pdf.name}}</b></a>
                                                                    {% endfor%}
                                                                </div>
                                                                </div>
            </div>
        </div> <!-- product -->
    {% endfor %}
{% endblock page %}

local_apps/petricko/templates/petricko/search.html
{% extends "petricko/base.html" %}
{% load cms_tags sekizai_tags menu_tags %}
{% load thumbnail %}
{% block page %}
<h2 class="h2_s">Výsledky vyhledávání</h2>
{% for result in results_list %}

    {% if result.1 == "Subcategory"%}
        {% for item in result.2 %}
                                                        <div class="product">
                                                    <h3>{{item.name}}</h3>
                                                    {% for article in item.article_set.all %}
                                                        
                                                            <div class="product_image">
                                                                <img src="{% thumbnail article.img 314x149 box=article.img_crop crop detail %}">
                                                            </div> <!-- product_image -->
                                                            <div class="product_content">
                                                                <p>{{ article.description|linebreaksbr }}</p>
                                                                <div class="product_bar">
                                                                     <hr class="product_hr" />
                                                                <div class="product_files">
                                                                    {% for pdf in product.pdf_set.all %}
                                                                        <a href="{{pdf.pdf_file.url}}"><img src="/static/petricko/img/pdf_icon.png" alt="{{pdf.name}}"><b>{{pdf.name}}</b></a>
                                                                    {% endfor%}
                                                                </div>
                                                                </div>
                                                            </div>
                                                      
                                                    {% endfor %}
                                                      </div> <!-- product -->
        {% endfor %}
    {% endif %}
    {% if result.1 == "New" %}
        {% for item in result.2 %}
                                                      <div class="new_date">{{ item.get_created_at }}</div> <!-- new_date -->
                                                    <div class="news_sub">
                                                    <h2>{{ item.name }}</h2>
                                                    <div class="cistic"></div><!-- cistic -->
                                                    <img id="new_detail_img" src="{% thumbnail new.img 286x230 box=new.img_crop crop detail %}">

                                                    <div id="new_detail_content">
                                                        <p>{{item.description}}</p>
                                                        <p>{{item.content}}</p>
                                                        <p><br /></p>
                                                        <p class="cist_cele"><a href="/#zadni_lajna_n"><span>Zpět na hlavní stranu</span></a></p>
                                                    </div>
                                                    </div><!-- news_sub -->
                                                    <div style="clear:both;"></div>
                                                      
        {% endfor %}
    {% endif %}
    {% if result.1 == "Product" %}
        {% for item in result.2 %}
                                                      <div class="product">
                                                        <div class="product_image">
                                                            <img src="{% thumbnail item.img 314x159 box=product.img_crop crop detail %}">
                                                        </div> <!-- product_image -->
                                                        <div class="product_content">
                                                            <h3>{{item.name}}</h3>
                                                            <p>{{item.description|linebreaksbr}}</p>
                                                        
                                                            <div class="product_bar">
                                                                <div class="product_files"></div>
                                                                {% if item.link_to_shop %}
                                                                <div class="product_on_eshop">
                                                                    <p><a href="{{item.link_to_shop}}">Nakupte u nás</a><p>
                                                                </div>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                    </div> <!-- product -->                                                            
        {% endfor %}
    {% endif %}
    {% if result.1 == "Category" %}
        {% for item in result.2 %}

                  <div class="product"><a href="/{{item.url_key}}"><h3>Kategori {{item.name}}</h3></a></div>
        {% endfor %}
    {% endif %}
{% endfor %}
{% endblock page %}

local_apps/petricko/templates/petricko/snippets/news.html
{% load thumbnail %}

<div class="predni_lajna"><!-- --></div><h2>Novinky</h2><div id="zadni_lajna_n"><!-- --></div>
{{news_list}}
{% for new in new_list %}
    <div class="new">
        <div class="new_date">{{ new.get_created_at }}</div> <!-- new_date -->
        <a href="{% url petricko.new new.url_key %}"><h3>{{ new.name }}</h3></a>
        <div class="cistic"></div><!-- cistic -->
        <div class="new_container">
            <img src="{% thumbnail new.img 143x115 box=new.img_crop crop detail %}">
            <div class="new_container_p">
                <p class="desriptions">{{ new.description }}</p>
                
                <p class="cist_cele"><a href="{% url petricko.new new.url_key %}"><span>Číst celé</span></a></p>
            </div>
        </div> <!-- new_container -->
        <hr class="new_hr">
    </div> <!-- new -->
{% endfor %}